import 'package:flutter/foundation.dart';

/// Modelo de dados para representação das Missões Pedagógicas dos Estandes da Feira de Ciências.
@immutable
class StandMission {
  final String id;
  final String standId;
  final int number;
  final String title;
  final String objective;
  final String componentsInfo;
  final String victoryCriteria;
  final String failureFeedback;
  final String voltsMediation;

  const StandMission({
    required this.id,
    required this.standId,
    required this.number,
    required this.title,
    required this.objective,
    required this.componentsInfo,
    required this.victoryCriteria,
    required this.failureFeedback,
    required this.voltsMediation,
  });

  static List<StandMission> get estande3Missions => const [
        StandMission(
          id: 'liga_desliga_m1',
          standId: 'liga_desliga',
          number: 1,
          title: 'Luz sob comando',
          objective: 'A equipe da recepção quer controlar a luminária sem desconectar fios toda vez. Inclua uma chave SPST no próprio caminho da lâmpada e mostre que ela cria ou interrompe o percurso conforme abre e fecha.',
          componentsInfo: 'Bateria (4.5V), Interruptor SPST, Lâmpada e Fios condutores',
          victoryCriteria: 'Chave aberta apaga; fechada acende.',
          failureFeedback: 'O interruptor SPST precisa estar no caminho da corrente.',
          voltsMediation: 'Interruptor aberto = caminho interrompido = sem corrente. Fechado = caminho completo = corrente flui.',
        ),
        StandMission(
          id: 'liga_desliga_m2',
          standId: 'liga_desliga',
          number: 2,
          title: 'Preveja a chave',
          objective: 'Dois cartazes mostram a mesma lâmpada em estados diferentes de chave. Sem energizar, leia os símbolos, registre a sua aposta e só então revele se o caminho está completo ou interrompido.',
          componentsInfo: 'Circuito montado com interruptor e lâmpada',
          victoryCriteria: 'Previsões e justificativas corretas.',
          failureFeedback: 'Circuito aberto interrompe a passagem da corrente.',
          voltsMediation: 'Símbolo com intervalo = chave aberta (sem corrente). Linha contínua = chave fechada (corrente flui).',
        ),
        StandMission(
          id: 'liga_desliga_m3',
          standId: 'liga_desliga',
          number: 3,
          title: 'Quem controla qual luz?',
          objective: 'Duas chaves foram instaladas sem etiqueta na pressa da montagem. Planeje uma investigação justa — mudando uma coisa por vez — para descobrir qual comando pertence a cada luminária e preparar as etiquetas da equipe.',
          componentsInfo: '2 Interruptores sem etiqueta, 2 Lâmpadas e Fonte de energia',
          victoryCriteria: 'Mapa correto com testes controlados.',
          failureFeedback: 'Teste um interruptor por vez e observe qual luz responde.',
          voltsMediation: 'Teste uma chave por vez. Assim você sabe qual controla qual luz — sem duvidar do resultado.',
        ),
        StandMission(
          id: 'liga_desliga_m4',
          standId: 'liga_desliga',
          number: 4,
          title: 'Chave no lugar errado',
          objective: 'A lâmpada continua acesa mesmo com a chave aberta, porque a corrente encontrou um desvio. Reconheça por que esse comando não tem efeito e coloque-o no ponto em que ele realmente consegue interromper o ramo da carga.',
          componentsInfo: 'Montagem com interruptor em desvio paralelo',
          victoryCriteria: 'SPST reposicionado em série.',
          failureFeedback: 'Essa chave em paralelo não interrompe a corrente da lâmpada.',
          voltsMediation: 'Chave em série: corta a corrente. Chave em paralelo: a corrente desvia e ignora o comando.',
        ),
        StandMission(
          id: 'liga_desliga_m5',
          standId: 'liga_desliga',
          number: 5,
          title: 'Luz de chamada',
          objective: 'Na bancada de dúvidas, a luz deve avisar somente enquanto alguém pressiona o botão. Monte esse comando momentâneo e diferencie sua função da de um interruptor que permanece na posição escolhida.',
          componentsInfo: 'Bateria, botão de pressão, lâmpada',
          victoryCriteria: 'Estado acompanha o botão.',
          failureFeedback: 'O botão de pressão deve manter a luz acesa apenas durante a pressão contínua.',
          voltsMediation: 'Push-button: fecha ao pressionar, abre ao soltar. SPST: mantém o estado escolhido até mudar.',
        ),
      ];

  static List<StandMission> get ruasMaqueteMissions => const [
        StandMission(
          id: 'ruas_maquete_m1',
          standId: 'ruas_maquete',
          number: 1,
          title: 'Primeiro poste',
          objective: 'Liga bateria, fios e o poste-lâmpada.',
          componentsInfo: 'Bateria 4.5V, 1 lâmpada de poste, fios condutores',
          victoryCriteria: 'Poste iluminado com retorno.',
          failureFeedback: 'Certifique-se de conectar a lâmpada do poste entre os dois polos da fonte.',
          voltsMediation: 'Todo circuito precisa de ida e volta. Sem o fio de retorno, a corrente não circula.',
        ),
        StandMission(
          id: 'ruas_maquete_m2',
          standId: 'ruas_maquete',
          number: 2,
          title: 'Uma segunda luz',
          objective: 'Monta série e paralelo, prevê brilho e retirada de lâmpada, depois testa.',
          componentsInfo: 'Circuito comutável com opções em série e em paralelo',
          victoryCriteria: 'Compara topologias observando.',
          failureFeedback: 'Em série o brilho cai e a remoção apaga ambos; em paralelo os ramos são independentes.',
          voltsMediation: 'Série: tensão dividida, cargas dependentes. Paralelo: tensão completa em cada carga, independentes.',
        ),
        StandMission(
          id: 'ruas_maquete_m3',
          standId: 'ruas_maquete',
          number: 3,
          title: 'Casa em manutenção',
          objective: 'Abre uma casa numa rede que apaga tudo e segue os ramos.',
          componentsInfo: 'Circuito residencial com ligação inadequada em série',
          victoryCriteria: 'Encontra ligação em série indevida.',
          failureFeedback: 'Cada casa deve estar em seu próprio ramo paralelo para permitir desligamento isolado.',
          voltsMediation: 'Cada ponto de carga em ramo paralelo próprio. Assim um pode ser desligado sem apagar os outros.',
        ),
        StandMission(
          id: 'ruas_maquete_m4',
          standId: 'ruas_maquete',
          number: 4,
          title: 'Bairro em funcionamento',
          objective: 'Usa junções para construir dois postes e duas casas em quatro ramos.',
          componentsInfo: 'Fonte, 2 lâmpadas de casas, 2 lâmpadas de postes, junções de fios',
          victoryCriteria: 'Quatro cargas independentes.',
          failureFeedback: 'Todos os 4 ramos precisam se conectar de forma independente à linha de retorno.',
          voltsMediation: 'Cada ramo precisa de conexão própria à linha de retorno. Sem isso, a corrente não fecha o circuito.',
        ),
        StandMission(
          id: 'ruas_maquete_m5',
          standId: 'ruas_maquete',
          number: 5,
          title: 'Manutenção durante a visita',
          objective: 'Abre chave de uma casa ou remove lâmpada diante do visitante.',
          componentsInfo: 'Rede do bairro em paralelo com lâmpada removível',
          victoryCriteria: 'Outros ramos permanecem acesos.',
          failureFeedback: 'Em paralelo, remover uma carga interrompe apenas aquele ramo específico.',
          voltsMediation: 'Ramos paralelos são independentes: desligar um não afeta os outros.',
        ),
      ];

  static List<StandMission> get letrerosLedMissions => const [
        StandMission(
          id: 'letreros_led_m1',
          standId: 'letreros_led',
          number: 1,
          title: 'Placa de Saída',
          objective: 'Gira LED, conecta ânodo/cátodo e inclui resistor 680 Ω em série com 9 V.',
          componentsInfo: 'Bateria 9V, LED vermelho, Resistor 680Ω',
          victoryCriteria: 'LED aceso em corrente segura.',
          failureFeedback: 'Verifique a polaridade do LED: o ânodo deve ir no positivo e a corrente precisa do resistor de 680 Ω.',
          voltsMediation: 'LED sem resistor queima em segundos. Use 680 Ω com 9 V para limitar a corrente a ~13 mA.',
        ),
        StandMission(
          id: 'letreros_led_m2',
          standId: 'letreros_led',
          number: 2,
          title: 'E se o LED estiver invertido?',
          objective: 'Prevê o efeito, gira o LED apagado e testa.',
          componentsInfo: 'Letreiro apagado com LED em polaridade invertida',
          victoryCriteria: 'Compara polaridade e resultado.',
          failureFeedback: 'O LED no sentido inverso bloqueia a corrente.',
          voltsMediation: 'LED é diodo: conduz em um sentido só. Invertido, age como isolante e não acende.',
        ),
        StandMission(
          id: 'letreros_led_m3',
          standId: 'letreros_led',
          number: 3,
          title: 'Por que a placa não acende?',
          objective: 'Testa LED invertido, fio aberto e resistor fora do ramo por inspeção/medição.',
          componentsInfo: 'Bateria 9V, LED, resistores (68Ω, 680Ω, 6.8kΩ)',
          victoryCriteria: 'Descarta hipóteses com evidência.',
          failureFeedback: 'Testar e descartar as causas de falha com medições antes de energizar.',
          voltsMediation: 'Descarte uma hipótese por vez: polaridade → continuidade → resistor no ramo.',
        ),
        StandMission(
          id: 'letreros_led_m4',
          standId: 'letreros_led',
          number: 4,
          title: 'Brilho com responsabilidade',
          objective: 'Troca 68 Ω, 680 Ω e 6,8 kΩ na montagem real.',
          componentsInfo: '2 LEDs (Entrada e Saída), resistores de 68Ω, 680Ω, 6.8kΩ, bateria 9V',
          victoryCriteria: 'Escolhe 680 Ω por proteção e brilho.',
          failureFeedback: '68 Ω causa sobrecorrente e 6.8 kΩ deixa a luz fraca demais.',
          voltsMediation: 'I = V ÷ R. Com 9 V e 680 Ω → ~13 mA. Seguro para o LED. Com 68 Ω → ~132 mA. Queima.',
        ),
        StandMission(
          id: 'letreros_led_m5',
          standId: 'letreros_led',
          number: 5,
          title: 'Entrada e Saída',
          objective: 'Monta dois ramos LED+resistor e a banca remove um deles.',
          componentsInfo: 'Dois ramos de LED com resistores de limitação',
          victoryCriteria: 'Outro letreiro continua funcional.',
          failureFeedback: 'Em paralelo com resistores próprios, remover um ramo mantém o outro operacional.',
          voltsMediation: 'Ramos paralelos com resistores próprios são independentes. Remover um não afeta o outro.',
        ),
      ];

  /// Mantida por compatibilidade com código legado.
  static const String voltsMediationEstandeMovimentoMiniatura =
      'Luz e movimento são formas diferentes de energia geradas pela corrente elétrica. Vamos explorar o motor CC.';

  static List<StandMission> get movimentoMiniaturaMissions => const [
        StandMission(
          id: 'movimento_miniatura_m1',
          standId: 'movimento',
          number: 1,
          title: 'Ventilador do estande',
          objective: 'Conecta fonte e motor CC pelos terminais.',
          componentsInfo: 'Bateria, motor CC didático com hélice',
          victoryCriteria: 'Motor gira.',
          failureFeedback: 'Confira se ambos os terminais do motor estão conectados à fonte.',
          voltsMediation: 'Corrente elétrica gera campo magnético. Campo magnético faz o eixo do motor girar.',
        ),
        StandMission(
          id: 'movimento_miniatura_m2',
          standId: 'movimento',
          number: 2,
          title: 'Carrinho de ida e volta',
          objective: 'Prevê o sentido e troca os dois fios do motor.',
          componentsInfo: 'Bateria comutável, motor CC de tração do carrinho',
          victoryCriteria: 'Carrinho chega ao destino.',
          failureFeedback: 'Inverta a polaridade para alterar o sentido do campo magnético e da rotação.',
          voltsMediation: 'Inverta os terminais = inverte a corrente = inverte o campo = motor gira no sentido oposto.',
        ),
        StandMission(
          id: 'movimento_miniatura_m3',
          standId: 'movimento',
          number: 3,
          title: 'Carrinho parado',
          objective: 'Executa testes de fonte, chave e continuidade para achar mau contato.',
          componentsInfo: 'Bateria, motor CC, chave e terminais com defeito oculto',
          victoryCriteria: 'Falha achada por testes.',
          failureFeedback: 'Siga a sequência de testes (fonte, chave, terminais) para localizar a abertura.',
          voltsMediation: 'Diagnóstico em sequência: fonte → chave → terminais → carga. Nunca pule etapas.',
        ),
        StandMission(
          id: 'movimento_miniatura_m4',
          standId: 'movimento',
          number: 4,
          title: 'Motor sob comando',
          objective: 'Insere push-button em série e LED+resistor em paralelo.',
          componentsInfo: 'Bateria, motor CC, botão de pressão, LED indicador, resistor 680 Ω',
          victoryCriteria: 'Motor e indicador respondem juntos.',
          failureFeedback: 'O botão controla o conjunto e o LED necessita de resistor de proteção.',
          voltsMediation: 'Push-button em série controla o motor. LED em paralelo indica sem interferir na corrente principal.',
        ),
        StandMission(
          id: 'movimento_miniatura_m5',
          standId: 'movimento',
          number: 5,
          title: 'Mostre o movimento',
          objective: 'Visitante pressiona botão; jogador troca polaridade para escolher rota.',
          componentsInfo: 'Montagem completa com botão e reversão de polaridade',
          victoryCriteria: 'Explica comando e reversão.',
          failureFeedback: 'Demonstre a função do botão de acionamento e a rotação por polaridade.',
          voltsMediation: 'Botão: aciona ou corta o circuito. Polaridade: determina a direção. Dois controles distintos.',
        ),
      ];

  /// Mantida por compatibilidade com código legado.
  static const String voltsMediationEstandeMedeTestaExplica =
      'Medir é enxergar o invisível: o multímetro revela quanta tensão e quanta corrente estão presentes no circuito.';

  static List<StandMission> get medeTestaExplicaMissions => const [
        StandMission(
          id: 'mede_testa_m1',
          standId: 'mede_testa',
          number: 1,
          title: 'Tensão da bateria',
          objective: 'Prende voltímetro em paralelo aos polos da bateria 9 V.',
          componentsInfo: 'Bateria 9V, voltímetro didático',
          victoryCriteria: 'Leitura aproximada de 9 V.',
          failureFeedback: 'O voltímetro deve ser conectado em paralelo com os terminais da fonte.',
          voltsMediation: 'Voltímetro em paralelo: compara potencial entre dois pontos sem interferir no circuito.',
        ),
        StandMission(
          id: 'mede_testa_m2',
          standId: 'mede_testa',
          number: 2,
          title: 'Queda na carga',
          objective: 'Posiciona ponteiras na carga, prevê leitura e testa.',
          componentsInfo: 'Bateria 9V, lâmpada de carga, voltímetro didático',
          victoryCriteria: 'Mede em paralelo e interpreta.',
          failureFeedback: 'Verifique exatamente entre quais dois pontos sobre a carga as pontas foram colocadas.',
          voltsMediation: 'Tensão sobre a carga = energia convertida em luz ou calor. Voltímetro em paralelo revela esse valor.',
        ),
        StandMission(
          id: 'mede_testa_m3',
          standId: 'mede_testa',
          number: 3,
          title: 'Corrente sob controle',
          objective: 'Abre ramo, encaixa amperímetro em série e gira potenciômetro.',
          componentsInfo: 'Resistor variável/potenciômetro, LED, amperímetro didático',
          victoryCriteria: 'Registra relação resistência/corrente.',
          failureFeedback: 'Maior resistência elétrica resulta em menor corrente no circuito (I = V / R).',
          voltsMediation: 'Amperímetro em série conta os elétrons que passam. Mais resistência = menos corrente (I = V ÷ R).',
        ),
        StandMission(
          id: 'mede_testa_m4',
          standId: 'mede_testa',
          number: 4,
          title: 'Escolha baseada em medida',
          objective: 'Troca resistores de LED, mede corrente e mantém valor seguro.',
          componentsInfo: 'Resistores de 68Ω, 680Ω e 6.8kΩ, LED, bateria 9V, amperímetro',
          victoryCriteria: 'Escolha justificada por valor medido.',
          failureFeedback: 'Selecione uma resistência que proteja a carga (10-15 mA) sem apagar o brilho.',
          voltsMediation: 'Meça antes de decidir. Entre 10–15 mA: LED seguro e brilhante. Fora dessa faixa: dano ou apagado.',
        ),
        StandMission(
          id: 'mede_testa_m5',
          standId: 'mede_testa',
          number: 5,
          title: 'Caso do LED fraco',
          objective: 'Mede fonte, resistor e polaridade para distinguir causas.',
          componentsInfo: 'Circuito com LED de brilho fraco, multímetro, painel de hipóteses',
          victoryCriteria: 'Relato à banca usa evidência.',
          failureFeedback: 'Uma conclusão científica deve utilizar dados medidos com precisão para descartar hipóteses.',
          voltsMediation: 'Uma conclusão científica precisa de evidência medida, não de intuição. Meça a tensão, a resistência e a polaridade para eliminar hipóteses.',
        ),

        // 08. Circuito Seguro (Missões M1 a M5)
        StandMission(
          id: 'circuito_seguro_m1',
          standId: 'circuito_seguro',
          number: 1,
          title: 'Alerta de Curto',
          objective: 'Identificar caminho de menor resistência que desvia da carga e sobrecarrega a fonte.',
          componentsInfo: 'Bateria 9V, LED de segurança, Resistor 680Ω, Fio em curto paralelo',
          victoryCriteria: 'Curto removido e corrente segura restabelecida na carga.',
          failureFeedback: 'O fio de curto cria um atalho de resistência quase nula, impedindo a corrente de passar pela carga e drenando a bateria.',
          voltsMediation: 'A eletricidade sempre procura o caminho mais fácil. Um curto desvia toda a energia da carga e aquece a fonte!',
        ),
        StandMission(
          id: 'circuito_seguro_m2',
          standId: 'circuito_seguro',
          number: 2,
          title: 'Continuidade & Fio Rompido',
          objective: 'Localizar ponto de descontinuidade física usando pontas de teste e restabelecer o percurso.',
          componentsInfo: 'Bateria 9V, Lâmpada de sinalização, 3 ramos de fiação, Pontas de prova de continuidade',
          victoryCriteria: 'Ramo rompido identificado e reparado com continuidade comprovada.',
          failureFeedback: 'Se houver qualquer quebra no condutor, o circuito fica aberto e os elétrons não conseguem circular.',
          voltsMediation: 'O teste de continuidade confirma se o caminho de ida e volta está 100% íntegro de terminal a terminal.',
        ),
        StandMission(
          id: 'circuito_seguro_m3',
          standId: 'circuito_seguro',
          number: 3,
          title: 'Fusível Didático',
          objective: 'Inserir fusível em série com filamento visível e selecionar a capacidade de proteção correta.',
          componentsInfo: 'Bateria 9V, Porta-fusível transparente, Fusíveis de 100mA e 1A, Lâmpada de carga',
          victoryCriteria: 'Fusível correto instalado e operando dentro da margem de segurança.',
          failureFeedback: 'Fusíveis com corrente muito baixa queimam sem motivo; fusíveis muito altos não protegem os componentes sensíveis.',
          voltsMediation: 'O fusível é o herói do circuito: ele se sacrifica (fundindo o filamento) para salvar os componentes caros de uma sobrecorrente.',
        ),
        StandMission(
          id: 'circuito_seguro_m4',
          standId: 'circuito_seguro',
          number: 4,
          title: 'Proteção & Sinalização Dupla',
          objective: 'Montar circuito com chave seccionadora protegida, fusível de proteção, LED e alarme sonoro.',
          componentsInfo: 'Chave seccionadora de segurança (flip guard), Fusível 250mA, LED verde e Buzzer',
          victoryCriteria: 'Chave de segurança armada e cargas duplas acionadas com proteção total.',
          failureFeedback: 'A chave deve seccionar a alimentação primária antes de qualquer ramo de carga.',
          voltsMediation: 'Em painéis industriais e na nossa feira, uma chave com trava impede acionamentos acidentais e isola a bancada com segurança.',
        ),
        StandMission(
          id: 'circuito_seguro_m5',
          standId: 'circuito_seguro',
          number: 5,
          title: 'Vistoria Geral da Equipe',
          objective: 'Auditar montagem da feira, diagnosticar e sanar 3 anomalias para liberação aos visitantes.',
          componentsInfo: 'Circuito completo pré-feira, Painel de checklist de inspeção de segurança',
          victoryCriteria: 'Todas as falhas sanadas e bancada certificada pela Equipe Segurança.',
          failureFeedback: 'Inspecione a integridade dos fios, o estado do fusível e garanta que não há curto antes de liberar a bancada.',
          voltsMediation: 'Uma boa vistoria salva a feira de ciências! Antes de abrir ao público, conferimos curto, continuidade e proteção.',
        ),
      ];
}
